# Generated by Django 3.0.2 on 2020-01-27 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='quesition',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='quesition_text',
            new_name='question_text',
        ),
    ]
